### ISSUE TITLE
Latest version error - 'gradle-project/app/src/main/java' is not a directory

### ISSUE THREAD

**Issue by texaggie96** [Commit451/UnityAndroidProjectToGradleProject#1]
I pulled from the repo and built the latest jar.  When I run 
java -jar unitytogradle.jar "./My CoolProject" 
I am getting this error:

java.lang.IllegalArgumentException: Source 'gradle-project/app/src/main/java' is not a directory
    at org.apache.commons.io.FileUtils.copyDirectoryToDirectory(FileUtils.java:1201)
    at com.commit451.unitytogradle.Main.moveFiles(Main.kt:72)
    at com.commit451.unitytogradle.Main.main(Main.kt:39)

This is odd for several reasons: 
1. i can clearly see that "gradle-project/app/src/main/java" clearly exists and is a directory.  
2. "FileUtils.copyDirectoryToDirectory(project.assets, structure.main)" 2 lines above (ln 70) works just fine.

Could it fail to detect "structure.java" as a valid "directory" b/c it has no children, whereas "structure.main" does?  Anybody else getting the same issue?  I am using OS X fyi.

**Comment by Jawnnypoo** [comment]
This is really strange. Do you think it possibly has to do with the fact that "My CoolProject" has spaces in it?
